# Generated by Django 4.2.4 on 2023-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('importance', models.CharField(choices=[('most_important', 'Most Important'), ('very_important', 'Very Important'), ('important', 'Important'), ('not_important', 'Not Important')], default='not_important', max_length=20)),
            ],
        ),
    ]
